@endpoint =  https://fr14b80676.execute-api.ap-southeast-1.amazonaws.com/prod
GET {{endpoint}}/hello/
###
POST {{endpoint}}/spaces/
Content-Type: application/json

{
  "location": "Tuban",
  "name": "Goa Ngerong"
}
###